### get all users
GET http://localhost:5000/users/


###get a user

GET http://localhost:5000/users/2

### Post data to database
POST http://localhost:5000/users
Content-Type: application/json

{
    "name" : "lala",
    "email" : "lala@gmail.com",
    "number": "012457"
}

### update a data
PUT http://localhost:5000/users/3
Content-Type: application/json

{
    "name" : "rasel",
    "email" : "rasel@gmail.com",
    "number" : "0124785"
}

### udate a single data
PATCH http://localhost:5000/users/5
Content-Type: application/json

{
    "name": "soikot",
    "email": "soikot@gmail.com"
}

### delete a data
DELETE http://localhost:5000/users/5