### lalal
@base_url = http://103.145.138.112:3000

### post category
POST {{base_url}}/categories
Content-Type: application/json

{
    "name": "electronic",
    "description": "this is the electronic products"
}

### get all categories
GET {{base_url}}/categories

### get categories by id
GET {{base_url}}/categories/2

### update a categories
PUT {{base_url}}/categories/3
Content-Type: application/json

{
    "name": "electronic",
    "description" : "this is electornic category"
}

### delete categories
DELETE {{base_url}}/categories/7