### lalal
@base_url = http://103.145.138.112:3000

### create customers
POST {{base_url}}/customers
Content-Type: application/json

{
    "name": "junayed",
    "email": "lala@gmail.com",
    "phone": "12570125",
    "address": "gajipur"
}

### get all customers
GET {{base_url}}/customers

### get customer by id
GET {{base_url}}/customers/3

### update customers data
PUT  {{base_url}}/customers/3
Content-Type: application/json

{
    "name": "imran",
    "email": "imran@gmail.com",
    "phone": "01785456",
    "address": "uttar badda"
}

### update just some customers data
PATCH {{base_url}}/customers/3
Content-Type: application/json

{
    "name": "lala"
}


### delete ustomers data
DELETE {{base_url}}/customers/6

