### base url
@base_url = http://103.145.138.112:3000

### create products
POST {{base_url}}/products
Content-Type: application/json

{
    "name": "men t-shirt",
    "price":"3000",
    "description": "modern three pics"
}

### get product
GET {{base_url}}/products

### get product by id
GET {{base_url}}/products/3


### update product by id
PUT {{base_url}}/products/5
Content-Type: application/json

{
    "name": "top nice t-shirt",
    "price":"1200",
    "description": "modern t shirt"
}

### update product by id
PATCH {{base_url}}/products/3
Content-Type: application/json

{
    "description":"modern t-shirt"
}