POST http://localhost:3000/products
Content-Type: application/json

{
    "name": "top nice t-shirt",
    "price":"1200",
    "description": "modern t shirt"
}

### get product
GET http://localhost:3000/products